[2025-02-14T17:50:30.816+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T17:50:30.833+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_to_snowflake.test_aws_connection manual__2025-02-14T17:50:25.851942+00:00 [queued]>
[2025-02-14T17:50:30.842+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_to_snowflake.test_aws_connection manual__2025-02-14T17:50:25.851942+00:00 [queued]>
[2025-02-14T17:50:30.842+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-14T17:50:30.895+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_aws_connection> on 2025-02-14 17:50:25.851942+00:00
[2025-02-14T17:50:30.929+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2829) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T17:50:30.940+0000] {standard_task_runner.py:72} INFO - Started process 2830 to run task
[2025-02-14T17:50:30.939+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_to_snowflake', 'test_aws_connection', 'manual__2025-02-14T17:50:25.851942+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/web_to_snowflake.py', '--cfg-path', '/tmp/tmpud5dably']
[2025-02-14T17:50:30.949+0000] {standard_task_runner.py:105} INFO - Job 209: Subtask test_aws_connection
[2025-02-14T17:50:31.053+0000] {task_command.py:467} INFO - Running <TaskInstance: web_to_snowflake.test_aws_connection manual__2025-02-14T17:50:25.851942+00:00 [running]> on host 715f5b9093d1
[2025-02-14T17:50:31.157+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_to_snowflake' AIRFLOW_CTX_TASK_ID='test_aws_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T17:50:25.851942+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T17:50:25.851942+00:00'
[2025-02-14T17:50:31.161+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T17:50:31.201+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-14T17:50:31.202+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-02-14T17:50:33.083+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-02-14T17:50:33.085+0000] {logging_mixin.py:190} INFO - Objects found: ['importFiles/2009q1/num.txt', 'importFiles/2009q1/pre.txt', 'importFiles/2009q1/readme.htm', 'importFiles/2009q1/sub.txt', 'importFiles/2009q1/tag.txt']
[2025-02-14T17:50:33.099+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-14T17:50:33.131+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T17:50:33.132+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=web_to_snowflake, task_id=test_aws_connection, run_id=manual__2025-02-14T17:50:25.851942+00:00, execution_date=20250214T175025, start_date=20250214T175030, end_date=20250214T175033
[2025-02-14T17:50:33.195+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T17:50:33.254+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T17:50:33.255+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
