[2025-02-14T16:56:57.826+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T16:56:57.836+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_to_snowflake.test_aws_connection manual__2025-02-14T16:56:54.087305+00:00 [queued]>
[2025-02-14T16:56:57.842+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_to_snowflake.test_aws_connection manual__2025-02-14T16:56:54.087305+00:00 [queued]>
[2025-02-14T16:56:57.842+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-14T16:56:57.851+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_aws_connection> on 2025-02-14 16:56:54.087305+00:00
[2025-02-14T16:56:57.884+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2256) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T16:56:57.889+0000] {standard_task_runner.py:72} INFO - Started process 2257 to run task
[2025-02-14T16:56:57.888+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_to_snowflake', 'test_aws_connection', 'manual__2025-02-14T16:56:54.087305+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/web_to_snowflake.py', '--cfg-path', '/tmp/tmpa5p2ku3f']
[2025-02-14T16:56:57.895+0000] {standard_task_runner.py:105} INFO - Job 198: Subtask test_aws_connection
[2025-02-14T16:56:58.016+0000] {task_command.py:467} INFO - Running <TaskInstance: web_to_snowflake.test_aws_connection manual__2025-02-14T16:56:54.087305+00:00 [running]> on host 715f5b9093d1
[2025-02-14T16:56:58.103+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_to_snowflake' AIRFLOW_CTX_TASK_ID='test_aws_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T16:56:54.087305+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T16:56:54.087305+00:00'
[2025-02-14T16:56:58.105+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T16:56:58.126+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-14T16:56:58.127+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-02-14T16:56:59.656+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-02-14T16:56:59.658+0000] {logging_mixin.py:190} INFO - Objects found: ['importFiles/2009q1/num.txt', 'importFiles/2009q1/pre.txt', 'importFiles/2009q1/readme.htm', 'importFiles/2009q1/sub.txt', 'importFiles/2009q1/tag.txt']
[2025-02-14T16:56:59.660+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-14T16:56:59.679+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T16:56:59.680+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=web_to_snowflake, task_id=test_aws_connection, run_id=manual__2025-02-14T16:56:54.087305+00:00, execution_date=20250214T165654, start_date=20250214T165657, end_date=20250214T165659
[2025-02-14T16:56:59.722+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T16:56:59.794+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T16:56:59.796+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
