[2025-02-14T05:29:22.361+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T05:29:22.374+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_to_snowflake.create_file_format manual__2025-02-14T05:29:12.711901+00:00 [queued]>
[2025-02-14T05:29:22.381+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_to_snowflake.create_file_format manual__2025-02-14T05:29:12.711901+00:00 [queued]>
[2025-02-14T05:29:22.381+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-14T05:29:22.389+0000] {taskinstance.py:2889} INFO - Executing <Task(SnowflakeOperator): create_file_format> on 2025-02-14 05:29:12.711901+00:00
[2025-02-14T05:29:22.397+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=189) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T05:29:22.399+0000] {standard_task_runner.py:72} INFO - Started process 190 to run task
[2025-02-14T05:29:22.400+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_to_snowflake', 'create_file_format', 'manual__2025-02-14T05:29:12.711901+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/web_to_snowflake.py', '--cfg-path', '/tmp/tmpagkgveiu']
[2025-02-14T05:29:22.403+0000] {standard_task_runner.py:105} INFO - Job 149: Subtask create_file_format
[2025-02-14T05:29:22.452+0000] {task_command.py:467} INFO - Running <TaskInstance: web_to_snowflake.create_file_format manual__2025-02-14T05:29:12.711901+00:00 [running]> on host 548064e9bd3b
[2025-02-14T05:29:22.532+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_to_snowflake' AIRFLOW_CTX_TASK_ID='create_file_format' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T05:29:12.711901+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T05:29:12.711901+00:00'
[2025-02-14T05:29:22.534+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T05:29:22.552+0000] {sql.py:278} INFO - Executing: 
    CREATE OR REPLACE FILE FORMAT my_csv_format
        TYPE = 'CSV'
        FIELD_DELIMITER = ','
        SKIP_HEADER = 1
        NULL_IF = ('NULL', 'null')
        EMPTY_FIELD_AS_NULL = TRUE
        DATE_FORMAT = 'YYYY-MM-DD';
    
[2025-02-14T05:29:22.566+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-02-14T05:29:22.574+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-02-14T05:29:22.575+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-02-14T05:29:22.577+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-02-14T05:29:22.578+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-02-14T05:29:23.033+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T05:29:23.037+0000] {sql.py:553} INFO - Running statement: CREATE OR REPLACE FILE FORMAT my_csv_format
        TYPE = 'CSV'
        FIELD_DELIMITER = ','
        SKIP_HEADER = 1
        NULL_IF = ('NULL', 'null')
        EMPTY_FIELD_AS_NULL = TRUE
        DATE_FORMAT = 'YYYY-MM-DD';, parameters: None
[2025-02-14T05:29:23.154+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T05:29:23.155+0000] {sql.py:562} INFO - Rows affected: 1
[2025-02-14T05:29:23.157+0000] {snowflake.py:447} INFO - Rows affected: 1
[2025-02-14T05:29:23.157+0000] {snowflake.py:448} INFO - Snowflake query id: 01ba6169-3202-c610-0005-f9060002e066
[2025-02-14T05:29:23.228+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T05:29:23.232+0000] {connection.py:789} INFO - closed
[2025-02-14T05:29:23.282+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-02-14T05:29:23.365+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T05:29:23.366+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=web_to_snowflake, task_id=create_file_format, run_id=manual__2025-02-14T05:29:12.711901+00:00, execution_date=20250214T052912, start_date=20250214T052922, end_date=20250214T052923
[2025-02-14T05:29:23.418+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T05:29:23.452+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T05:29:23.454+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
