[2025-02-14T05:08:19.272+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T05:08:19.287+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_to_snowflake.test_snowflake_connection manual__2025-02-14T05:08:13.831160+00:00 [queued]>
[2025-02-14T05:08:19.297+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_to_snowflake.test_snowflake_connection manual__2025-02-14T05:08:13.831160+00:00 [queued]>
[2025-02-14T05:08:19.298+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-14T05:08:19.308+0000] {taskinstance.py:2889} INFO - Executing <Task(SnowflakeOperator): test_snowflake_connection> on 2025-02-14 05:08:13.831160+00:00
[2025-02-14T05:08:19.316+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T05:08:19.319+0000] {standard_task_runner.py:72} INFO - Started process 76 to run task
[2025-02-14T05:08:19.327+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_to_snowflake', 'test_snowflake_connection', 'manual__2025-02-14T05:08:13.831160+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/web_to_snowflake.py', '--cfg-path', '/tmp/tmplf7n6j90']
[2025-02-14T05:08:19.333+0000] {standard_task_runner.py:105} INFO - Job 128: Subtask test_snowflake_connection
[2025-02-14T05:08:19.372+0000] {task_command.py:467} INFO - Running <TaskInstance: web_to_snowflake.test_snowflake_connection manual__2025-02-14T05:08:13.831160+00:00 [running]> on host 548064e9bd3b
[2025-02-14T05:08:19.446+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_to_snowflake' AIRFLOW_CTX_TASK_ID='test_snowflake_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T05:08:13.831160+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T05:08:13.831160+00:00'
[2025-02-14T05:08:19.450+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T05:08:19.484+0000] {sql.py:278} INFO - Executing: SELECT CURRENT_TIMESTAMP;
[2025-02-14T05:08:19.493+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-02-14T05:08:19.502+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-02-14T05:08:19.505+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-02-14T05:08:19.509+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-02-14T05:08:19.510+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-02-14T05:08:20.869+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T05:08:20.871+0000] {sql.py:553} INFO - Running statement: SELECT CURRENT_TIMESTAMP;, parameters: None
[2025-02-14T05:08:21.001+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T05:08:21.002+0000] {sql.py:562} INFO - Rows affected: 1
[2025-02-14T05:08:21.007+0000] {snowflake.py:447} INFO - Rows affected: 1
[2025-02-14T05:08:21.008+0000] {snowflake.py:448} INFO - Snowflake query id: 01ba6154-3202-c60f-0005-f9060002c056
[2025-02-14T05:08:21.111+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T05:08:21.111+0000] {connection.py:789} INFO - closed
[2025-02-14T05:08:21.166+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-02-14T05:08:21.258+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T05:08:21.258+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=web_to_snowflake, task_id=test_snowflake_connection, run_id=manual__2025-02-14T05:08:13.831160+00:00, execution_date=20250214T050813, start_date=20250214T050819, end_date=20250214T050821
[2025-02-14T05:08:21.283+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T05:08:21.343+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T05:08:21.345+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
